# Generated by Django 2.2.5 on 2019-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_name', models.CharField(max_length=30)),
                ('victim_name', models.CharField(max_length=20)),
                ('victim_address', models.CharField(max_length=30)),
                ('victim_ph', models.CharField(max_length=30)),
                ('victim_age', models.CharField(max_length=30)),
                ('cri_loc', models.CharField(max_length=30)),
                ('cri_date', models.DateField()),
                ('cri_sec', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('pol_name', models.CharField(max_length=30)),
                ('pol_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lost_found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('loc', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='petrolling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=30)),
                ('pet_area', models.CharField(max_length=30)),
                ('pol_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='police_info',
            fields=[
                ('pol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pol_name', models.CharField(max_length=20)),
                ('pol_post', models.CharField(max_length=10)),
                ('pol_join', models.DateField()),
                ('pol_pass', models.CharField(max_length=10)),
                ('pol_dept', models.CharField(max_length=20)),
                ('secret_key', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'police',
            },
        ),
    ]
