# Generated by Django 2.2.5 on 2019-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='off_day',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
