# Generated by Django 2.2.5 on 2019-09-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_police_info_off_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police_info',
            name='off_day',
        ),
    ]
