# Generated by Django 2.2.5 on 2019-09-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_remove_police_info_off_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lost_found',
        ),
    ]
