# Generated by Django 2.2.5 on 2019-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_delete_lost_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_1', models.CharField(default=' ', max_length=20)),
                ('notice_2', models.CharField(default=' ', max_length=20)),
                ('notice_3', models.CharField(default=' ', max_length=20)),
                ('notice_4', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
