# Generated by Django 2.2.5 on 2019-09-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='off_day',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.criminal')),
            ],
        ),
    ]
