# Generated by Django 2.2.5 on 2019-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0006_auto_20190929_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='schedule',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
