# Generated by Django 2.2.5 on 2019-10-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0008_today'),
    ]

    operations = [
        migrations.DeleteModel(
            name='today',
        ),
    ]
