# Generated by Django 2.2.5 on 2019-10-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0009_delete_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='duty_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
