# Generated by Django 2.2.5 on 2019-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0011_auto_20191002_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
