# Generated by Django 2.2.5 on 2019-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0012_auto_20191002_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='daily_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
