# Generated by Django 2.2.5 on 2019-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0013_police_info_daily_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='overtime',
            field=models.IntegerField(default=0),
        ),
    ]
