# Generated by Django 2.2.5 on 2019-10-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0014_police_info_overtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
