# Generated by Django 2.2.5 on 2019-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0016_criminal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='status',
            field=models.CharField(default='ongoing', max_length=20),
        ),
    ]
