# Generated by Django 2.2.5 on 2019-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0017_auto_20191003_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost_and_found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=100)),
                ('article_type', models.CharField(max_length=50)),
                ('loc_of_incedent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('doc_id', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=100)),
                ('pol_name', models.CharField(max_length=100)),
                ('pol_id', models.IntegerField()),
            ],
        ),
    ]
