# Generated by Django 2.2.5 on 2019-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0018_lost_and_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='notification',
        ),
    ]
