# Generated by Django 2.2.5 on 2019-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0019_auto_20191003_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost_and_found',
            name='police_station',
            field=models.CharField(default='NASHIK CITY POLICE STATION', max_length=40),
        ),
    ]
