# Generated by Django 2.2.5 on 2019-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0020_lost_and_found_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='clas',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
