# Generated by Django 2.2.5 on 2019-10-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0023_auto_20191007_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_info',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
    ]
