# Generated by Django 2.2.5 on 2019-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0024_police_info_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph', models.CharField(max_length=12)),
            ],
        ),
    ]
